# GhostMesh Container Compose Configuration
# Edge AI Security Copilot Services
# Compatible with both Docker and Podman
# 
# Documentation: docs/Project_README.md
# MQTT Configuration: docs/MQTT_Configuration.md

services:
  # Mock OPC UA Server for development and testing
  mock-opcua:
    build: ./mock-opcua
    container_name: ghostmesh-mock-opcua
    ports:
      - "4840:4840"
    restart: unless-stopped
    networks:
      - ghostmesh-network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: ghostmesh-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd:/mosquitto/config/passwd
      - ./mosquitto/acl.conf:/mosquitto/config/acl.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    environment:
      - MOSQUITTO_USERNAME=mosquitto
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mosquitto_pub", "-h", "localhost", "-t", "test", "-m", "healthcheck", "-u", "iot", "-P", "iotpass"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - ghostmesh-network

  # OPC UA to MQTT Gateway - Implemented in THE-60
  opcua2mqtt:
    build: ./opcua2mqtt
    container_name: ghostmesh-gateway
    depends_on:
      mosquitto:
        condition: service_healthy
      mock-opcua:
        condition: service_started
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=gateway
      - MQTT_PASSWORD=gatewaypass
    restart: unless-stopped
    networks:
      - ghostmesh-network

  # Anomaly Detector - Implemented in THE-62
  anomaly:
    build: ./anomaly
    container_name: ghostmesh-detector
    depends_on:
      mosquitto:
        condition: service_healthy
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=iot
      - MQTT_PASSWORD=iotpass
      - MQTT_QOS=1
    restart: unless-stopped
    networks:
      - ghostmesh-network

  # Policy Engine - Implemented in THE-63
  policy:
    build: ./policy
    container_name: ghostmesh-policy
    depends_on:
      mosquitto:
        condition: service_healthy
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=iot
      - MQTT_PASSWORD=iotpass
      - MQTT_QOS=1
    restart: unless-stopped
    networks:
      - ghostmesh-network

  # AI Explainer Service - Implemented in THE-67 (LLM Integration)
  explainer:
    build: ./explainer
    container_name: ghostmesh-explainer
    depends_on:
      mosquitto:
        condition: service_healthy
      llm-server:
        condition: service_healthy
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=explainer
      - MQTT_PASSWORD=explainerpass
      - MQTT_QOS=1
      - LLM_SERVER_URL=http://llm-server:8080
      - DEFAULT_USER_TYPE=hybrid
      - EXPLANATION_TIMEOUT=10
    restart: unless-stopped
    networks:
      - ghostmesh-network

  # LLM Server - Implemented in THE-67
  llm-server:
    build: ./llm-server
    container_name: ghostmesh-llm-server
    ports:
      - "8080:8080"
    volumes:
      - llm_models:/models
    environment:
      - MODEL_PATH=/models/tinyllama-1.1b-chat.gguf
    restart: unless-stopped
    networks:
      - ghostmesh-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Streamlit Dashboard - Implemented in THE-61
  dashboard:
    build: ./dashboard
    container_name: ghostmesh-dashboard
    ports:
      - "8501:8501"
    depends_on:
      mosquitto:
        condition: service_healthy
    environment:
      - MQTT_HOST=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=dashboard
      - MQTT_PASSWORD=dashboard123
    restart: unless-stopped
    networks:
      - ghostmesh-network

volumes:
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local
  llm_models:
    driver: local

networks:
  ghostmesh-network:
    driver: bridge
