# GhostMesh Container Compose Configuration
# Edge AI Security Copilot Services
# Compatible with both Docker and Podman
# 
# Documentation: docs/Project_README.md
# MQTT Configuration: docs/MQTT_Configuration.md
# Environment: Copy env.example to .env and customize

services:
  # Mock OPC UA Server for development and testing
  mock-opcua:
    build: ./mock-opcua
    container_name: ghostmesh-mock-opcua
    ports:
      - "4840:4840"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    networks:
      - ghostmesh-network

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: ghostmesh-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd:/mosquitto/config/passwd
      - ./mosquitto/acl.conf:/mosquitto/config/acl.conf
      - mosquitto_data:/mosquitto/data
      - mosquitto_logs:/mosquitto/log
    environment:
      - MOSQUITTO_USERNAME=mosquitto
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    networks:
      - ghostmesh-network

  # OPC UA to MQTT Gateway - Implemented in THE-60
  opcua2mqtt:
    build: ./opcua2mqtt
    container_name: ghostmesh-gateway
    depends_on:
      mosquitto:
        condition: service_started
      mock-opcua:
        condition: service_started
    environment:
      - MQTT_HOST=${MQTT_HOST:-mosquitto}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME_GATEWAY:-gateway}
      - MQTT_PASSWORD=${MQTT_PASSWORD_GATEWAY:-gatewaypass}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    networks:
      - ghostmesh-network

  # Anomaly Detector - Implemented in THE-62
  anomaly:
    build: ./anomaly
    container_name: ghostmesh-detector
    depends_on:
      mosquitto:
        condition: service_started
    environment:
      - MQTT_HOST=${MQTT_HOST:-mosquitto}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME_IOT:-iot}
      - MQTT_PASSWORD=${MQTT_PASSWORD_IOT:-iotpass}
      - MQTT_QOS=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    networks:
      - ghostmesh-network

  # Policy Engine - Implemented in THE-63
  policy:
    build: ./policy
    container_name: ghostmesh-policy
    depends_on:
      mosquitto:
        condition: service_started
    environment:
      - MQTT_HOST=${MQTT_HOST:-mosquitto}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME_IOT:-iot}
      - MQTT_PASSWORD=${MQTT_PASSWORD_IOT:-iotpass}
      - MQTT_QOS=1
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    networks:
      - ghostmesh-network

  # AI Explainer Service - Implemented in THE-67 (LLM Integration)
  explainer:
    build: ./explainer
    container_name: ghostmesh-explainer
    depends_on:
      mosquitto:
        condition: service_started
      llm-server:
        condition: service_started
    environment:
      - MQTT_HOST=${MQTT_HOST:-mosquitto}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME_EXPLAINER:-explainer}
      - MQTT_PASSWORD=${MQTT_PASSWORD_EXPLAINER:-explainerpass}
      - MQTT_QOS=1
      - LLM_SERVER_URL=${LLM_SERVER_URL:-http://llm-server:8080}
      - DEFAULT_USER_TYPE=${DEFAULT_USER_TYPE:-hybrid}
      - EXPLANATION_TIMEOUT=${EXPLANATION_TIMEOUT:-10}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.5'
        reservations:
          memory: 128M
          cpus: '0.25'
    networks:
      - ghostmesh-network

  # LLM Server - Implemented in THE-67
  llm-server:
    build: ./llm-server
    container_name: ghostmesh-llm-server
    ports:
      - "8080:8080"
    volumes:
      - llm_models:/models
    environment:
      - MODEL_PATH=${MODEL_PATH:-/models/tinyllama-1.1b-chat.gguf}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    networks:
      - ghostmesh-network

  # Streamlit Dashboard - Implemented in THE-61
  dashboard:
    build: ./dashboard
    container_name: ghostmesh-dashboard
    ports:
      - "8501:8501"
    depends_on:
      mosquitto:
        condition: service_started
    environment:
      - MQTT_HOST=${MQTT_HOST:-localhost}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - MQTT_USERNAME=${MQTT_USERNAME_DASHBOARD:-dashboard}
      - MQTT_PASSWORD=${MQTT_PASSWORD_DASHBOARD:-dashboard123}
      - STREAMLIT_SERVER_HEADLESS=${STREAMLIT_SERVER_HEADLESS:-true}
      - STREAMLIT_SERVER_ENABLE_CORS=${STREAMLIT_SERVER_ENABLE_CORS:-false}
      - STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION=${STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION:-false}
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
    networks:
      - ghostmesh-network

volumes:
  mosquitto_data:
    driver: local
  mosquitto_logs:
    driver: local
  llm_models:
    driver: local

networks:
  ghostmesh-network:
    driver: bridge
